# Creates (or refreshes the password of) a dedicated local Windows account
# for running ZenServer under the "专用本地账号" service-account tier — the
# officially-recommended least-privilege alternative to SYSTEM. Same
# New-LocalUser / Set-LocalUser idempotent pattern setup-share-mode-b.ps1
# already uses for share accounts.
#
# This script only creates the account. Permission grants (log-on-as-a-service,
# {ZenInstall} read, {ZenData} read+write) happen in zen-service-install.ps1
# right before `sc create`; the urlacl reservation is zen-urlacl-add.ps1. Both
# are run separately against the account name this script returns.
#
# Parameters (stdin JSON):
#   Username <string>  local account name to create, e.g. "zen-svc-ab12cd".
#   Password <string>  password to set. Generated by the caller
#                       (core::zen::service_account::create_dedicated_account)
#                       and stored in SecretStore — never logged here.
#
# Output (single JSON object on stdout):
#   { "ok": true, "username": "zen-svc-ab12cd", "created": true }
#   { "ok": false, "message": "..." }

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
chcp 65001 | Out-Null

$ErrorActionPreference = 'Stop'

try {
    $p = [Console]::In.ReadLine() | ConvertFrom-Json
    $Username = $p.Username
    $Password = $p.Password
    if ([string]::IsNullOrWhiteSpace($Username)) {
        @{ ok = $false; message = "Username is required" } | ConvertTo-Json -Compress
        exit 0
    }
    if ([string]::IsNullOrWhiteSpace($Password)) {
        @{ ok = $false; message = "Password is required" } | ConvertTo-Json -Compress
        exit 0
    }

    $secure = ConvertTo-SecureString -String $Password -AsPlainText -Force
    $existing = Get-LocalUser -Name $Username -ErrorAction SilentlyContinue
    if ($existing) {
        Set-LocalUser -Name $Username -Password $secure -PasswordNeverExpires $true
        $created = $false
    } else {
        New-LocalUser -Name $Username -Password $secure -PasswordNeverExpires -AccountNeverExpires `
            -UserMayNotChangePassword -Description 'Volo ZenServer dedicated service account' | Out-Null
        # Not added to any admin/privileged group — the whole point of this
        # tier is running with only the permissions zen-service-install.ps1
        # explicitly grants (log-on-as-a-service via sc create obj=, plus the
        # icacls grants on {ZenInstall}/{ZenData}).
        $created = $true
    }

    @{ ok = $true; username = $Username; created = $created } | ConvertTo-Json -Compress
}
catch {
    @{ ok = $false; message = "$($_.Exception.Message)" } | ConvertTo-Json -Compress
    exit 0
}
